[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    { name = "Your Name", email = "you@example.com" }
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "django (>=6.0.2,<7.0.0)", 
    "django-ninja (>=1.5.3,<2.0.0)", 
    "fastf1 (>=3.8.1,<4.0.0)", 
    "psycopg2-binary (>=2.9.11,<3.0.0)", 
    "python-dotenv (>=1.2.1,<2.0.0)", 
    "django-vite (>=3.1.0,<4.0.0)", 
    "inertia-django (>=1.2.0,<2.0.0)"
    ]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"