# Generated by Django 6.0.2 on 2026-03-01 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('circuit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='f1data.circuit')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='f1data.season')),
            ],
            options={
                'unique_together': {('season', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('R', 'Race'), ('Q', 'Qualifying'), ('S', 'Sprint'), ('FP1', 'Practice 1'), ('FP2', 'Practice 2'), ('FP3', 'Practice 3')], max_length=3)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='f1data.event')),
            ],
            options={
                'unique_together': {('event', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('permanent_number', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('team_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='f1data.team')),
            ],
        ),
        migrations.CreateModel(
            name='TrackMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_points', models.JSONField()),
                ('y_points', models.JSONField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_maps', to='f1data.circuit')),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField()),
                ('lap_time', models.DurationField(blank=True, null=True)),
                ('sector_1', models.DurationField(blank=True, null=True)),
                ('sector_2', models.DurationField(blank=True, null=True)),
                ('sector_3', models.DurationField(blank=True, null=True)),
                ('compound', models.CharField(blank=True, max_length=50)),
                ('stint', models.IntegerField(blank=True, null=True)),
                ('is_personal_best', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='f1data.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='f1data.session')),
            ],
            options={
                'unique_together': {('session', 'driver', 'lap_number')},
            },
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_position', models.IntegerField(blank=True, null=True)),
                ('finish_position', models.IntegerField(blank=True, null=True)),
                ('points', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('FIN', 'Finished'), ('DNF', 'Did Not Finish'), ('DSQ', 'Disqualified'), ('DNS', 'Did Not Start'), ('NC', 'Not Classified')], default='FIN', max_length=3)),
                ('fastest_lap', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='f1data.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='f1data.session')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='f1data.team')),
            ],
            options={
                'unique_together': {('session', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='TelemetryFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_ms', models.BigIntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('speed', models.FloatField(null=True)),
                ('gear', models.IntegerField(null=True)),
                ('throttle', models.FloatField(null=True)),
                ('brake', models.BooleanField(default=False)),
                ('drs', models.IntegerField(null=True)),
                ('lap_number', models.IntegerField(null=True)),
                ('compound', models.CharField(blank=True, max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_frames', to='f1data.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_frames', to='f1data.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'timestamp_ms'], name='f1data_tele_session_26d3f5_idx'), models.Index(fields=['session', 'driver', 'timestamp_ms'], name='f1data_tele_session_c4a51b_idx')],
            },
        ),
    ]
